version: '3.8'

services:
  postgres:
      image: postgres
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: diginv
      ports:
        - "5433:5432"
      volumes:
        # - ./storage/postgres:/var/lib/postgresql/data
        - ./sql/back.sql:/docker-entrypoint-initdb.d/init.sql

